### ISSUE TITLE
Play 1.1

### ISSUE THREAD

**Issue by vlastikcz** [crazyraindrop/auditlog#2]
Hello,
I'm working on my first Play project and this module is exactly what I need. But please, is this module compatible with Play 1.1? 

I'm trying to implement it into my project and I'm becoming an error 
"ClassCastException occured : models.MyModel cannot be cast to play.db.jpa.JPASupport". 

This error appears in my controller after **entity.save();** even if the model hasn't Auditable annotation. My application.conf setup is the same as in your wiki, module is loaded and the AuditLogEvent table was created.

Thank you.

Regards,
Vlastikcz

**Comment by crazyraindrop** [comment]
This module is just an example, so feel free to clone it and make whatever modifications you need. In order to make it work with 1.1 you probably just need to replace all JPASupport with GenericModel and run ant in module directory to rebuild it's jar
